### ISSUE TITLE
Backup Rake Aborts

### ISSUE THREAD

**Issue by pnelsonsr** [sameersbn/docker-gitlab#191]
When I upgraded to 7.4.3 (from 7.4.2) I tried to the do the backup part (as described in you Upgrading which has worked in the past).  This time the task aborts in the Dumping Repositories part.  Here is the error:
...
- python/mdc ... [DONE]
- python/mdc.wiki ... rake aborted!
  NoMethodError: undefined method `empty?' for nil:NilClass
  /home/git/gitlab/app/models/repository.rb:25:in`empty?'
  /home/git/gitlab/lib/backup/repository.rb:33:in `block in dump'
  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/relation/batches.rb:52:in`block (2 levels) in find_each'
  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/relation/batches.rb:52:in `each'
  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/relation/batches.rb:52:in`block in find_each'
  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/relation/batches.rb:125:in `find_in_batches'
  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/relation/batches.rb:51:in`find_each'
  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/querying.rb:9:in `find_each'
  /home/git/gitlab/lib/backup/repository.rb:10:in`dump'
  /home/git/gitlab/lib/tasks/gitlab/backup.rake:39:in `block (4 levels) in <top (required)>'
  /home/git/gitlab/lib/tasks/gitlab/backup.rake:11:in`block (3 levels) in <top (required)>'
  Tasks: TOP => gitlab:backup:repo:create
  (See full trace by running task with --trace)

Sorry for the output but I don't know how to just put up text.  Anyhow, what do you think the problem is?
