### ISSUE TITLE
NoMethodError (undefined method `theme_id=' for #<User id: @>):

### ISSUE THREAD

**Issue by FarhadF** [sameersbn/docker-gitlab#1386]
after upgrading from 9.x.x to 10.0.3 Im getting http 500 instead of login page.

```
Raven 2.5.3 configured not to capture errors: DSN not set
Raven 2.5.3 configured not to capture errors: DSN not set
Started GET "/" for 192.168.163.196 at 2017-10-22 04:59:40 +0000
Processing by RootController#index as HTML
Redirected to http://192.168.163.196:10080/users/sign_in
Filter chain halted as :redirect_unlogged_user rendered or redirected
Completed 302 Found in 8ms (ActiveRecord: 0.0ms)
Started GET "/users/sign_in" for 192.168.163.196 at 2017-10-22 04:59:42 +0000
Processing by SessionsController#new as HTML
Completed 500 Internal Server Error in 54ms (ActiveRecord: 3.5ms)

NoMethodError (undefined method `theme_id=' for #<User id: @>):
  app/controllers/sessions_controller.rb:20:in `new'
  lib/gitlab/i18n.rb:46:in `with_locale'
  lib/gitlab/i18n.rb:52:in `with_user_locale'
  app/controllers/application_controller.rb:326:in `set_locale'
  lib/gitlab/middleware/multipart.rb:93:in `call'
  lib/gitlab/request_profiler/middleware.rb:14:in `call'
  lib/gitlab/middleware/go.rb:17:in `call'
  lib/gitlab/etag_caching/middleware.rb:11:in `call'
  lib/gitlab/request_context.rb:18:in `call'
  lib/gitlab/metrics/requests_rack_middleware.rb:27:in `call'


StuckCiJobsWorker: Cleaning stuck builds
```
looks similar to this [https://gitlab.com/gitlab-org/gitlab-ce/issues/38324](Issue).
As the issue resolved using gitlabctl reconfigure, please advise how can I run an alternative as gitlabctl is not available in the docker image.

**Comment by robin112** [comment]
+1

**Comment by robin112** [comment]
i had the same issue , my migrate status showed some were down, i just re-ran the migrate command , and then 500 error was gone :)
