### ISSUE TITLE
metrics and profiling not working after upgrade to 14.0.5

### ISSUE THREAD

**Issue by shiresn** [sameersbn/docker-gitlab#2387]
not sure if this is related to upgrade , after upgrade to 14.0.5 admin area\Settings\Metrics and profiling stop working, 

in production log 

```
Started GET "/admin/application_settings/metrics_and_profiling" for 10.32.232.12 at 2021-07-17 01:03:34 +0000
Processing by Admin::ApplicationSettingsController#metrics_and_profiling as HTML
  Rendered layout layouts/admin.html.haml (Duration: 160.4ms | Allocations: 23320)
Completed 500 Internal Server Error in 182ms (ActiveRecord: 2.1ms | Elasticsearch: 0.0ms | Allocations: 31654)

ActionView::Template::Error (undefined local variable or method `prometheus_multiproc_dir' for #<ActionView::Base:0x00000000252128>
Did you mean?  prometheus_default_multiproc_dir):
    15:         - unless Gitlab::Metrics.metrics_folder_present?
    16:           .form-text.text-muted
    17:             %strong.cred= _("WARNING:")
    18:             = _("Environment variable %{code_start}%{environment_variable}%{code_end} does not exist or is not pointing to a valid directo
ry.").html_safe % { environment_variable: prometheus_multiproc_dir, code_start: '<code>'.html_safe, code_end: '</code>'.html_safe }
    19:             = link_to sprite_icon('question-o'), help_page_path('administration/monitoring/prometheus/gitlab_metrics', anchor: 'metrics-sh
ared-directory')
    20:     .form-group
    21:       = f.label :metrics_method_call_threshold, _('Method Call Threshold (ms)'), class: 'label-bold
```

after check gitlab doc [here ](https://docs.gitlab.com/ee/administration/monitoring/prometheus/gitlab_metrics.html#metrics-shared-directory)i add below env in docker run parameter ,it worked  but i'm not sure if this suitable to be default value in env?
prometheus_multiproc_dir=/dev/shm

**Comment by limpair** [comment]
I have same problems.
![image](https://user-images.githubusercontent.com/19998264/126031702-66936344-9491-4c23-a0f3-4621b75dec9e.png)
![image](https://user-images.githubusercontent.com/19998264/126031765-95671c90-41d6-46ea-9712-fff4a55a3e5e.png)

**Comment by paolomainardi** [comment]
Same problem here (and others), i'll try this fix.

**Comment by sue445** [comment]
I confirmed this problem at v13.12.4 too.

**Comment by paolomainardi** [comment]
Just to follow up on this, the fix works as expected

**Comment by paulknulst** [comment]
I encountered that error too. I can also confirm that the fix works!

**Comment by expectraon** [comment]
![image](https://user-images.githubusercontent.com/19955912/130624441-66aa6da0-0e54-436f-9373-4780d238249c.png)

In synology DS920+ DSM 7.0 environment When I applied the above solution,
the 500 error problem on the Metrics and profiling page was resolved.
thank you
