### ISSUE TITLE
[Need Help] NoMethodError: undefined method `default_group_visibility' for #<ApplicationSetting:0x0000000005387ca0>

### ISSUE THREAD

**Issue by marmartintsang** [sameersbn/docker-gitlab#1535]
When I upgrade my gitlab from 8 to 10.5.1, I got an error `NoMethodError: undefined method 'default_group_visibility' for #<ApplicationSetting:0x0000000007c40188>`  on Migrating database when starting gitlab. 

```
Initializing logdir...
Initializing datadir...
Installing configuration templates...
Configuring gitlab...
Configuring gitlab::database
Configuring gitlab::redis
Configuring gitlab::secrets...
Configuring gitlab::sidekiq...
Configuring gitlab::gitaly...
Configuring gitlab::monitoring...
Configuring gitlab::gitlab-workhorse...
Configuring gitlab::unicorn...
Configuring gitlab::timezone...
Configuring gitlab::rack_attack...
Configuring gitlab::ci...
Configuring gitlab::artifacts...
Configuring gitlab::lfs...
Configuring gitlab::uploads...
Configuring gitlab::mattermost...
Configuring gitlab::project_features...
Configuring gitlab::oauth...
Configuring gitlab::ldap...
Configuring gitlab::cron_jobs...
Configuring gitlab::backups...
Configuring gitlab::registry...
Configuring gitlab::pages...
Configuring gitlab-shell...
Configuring nginx...
Configuring nginx::gitlab...
Migrating database...
rake aborted!
NoMethodError: undefined method `default_group_visibility' for #<ApplicationSetting:0x0000000007c40188>
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.10/lib/active_model/attribute_methods.rb:433:in `method_missing'
/home/git/gitlab/lib/api/groups.rb:13:in `block (2 levels) in <class:Groups>'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-1.0.0/lib/grape/dsl/parameters.rb:65:in `instance_exec'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-1.0.0/lib/grape/dsl/parameters.rb:65:in `block in use'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-1.0.0/lib/grape/dsl/parameters.rb:61:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-1.0.0/lib/grape/dsl/parameters.rb:61:in `use'
/home/git/gitlab/lib/api/groups.rb:21:in `block (2 levels) in <class:Groups>'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-1.0.0/lib/grape/dsl/parameters.rb:65:in `instance_exec'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-1.0.0/lib/grape/dsl/parameters.rb:65:in `block in use'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-1.0.0/lib/grape/dsl/parameters.rb:61:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-1.0.0/lib/grape/dsl/parameters.rb:61:in `use'
/home/git/gitlab/lib/api/groups.rb:99:in `block (2 levels) in <class:Groups>'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-1.0.0/lib/grape/validations/params_scope.rb:34:in `instance_eval'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-1.0.0/lib/grape/validations/params_scope.rb:34:in `initialize'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-1.0.0/lib/grape/dsl/validations.rb:23:in `new'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-1.0.0/lib/grape/dsl/validations.rb:23:in `params'
/home/git/gitlab/lib/api/groups.rb:91:in `block in <class:Groups>'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-1.0.0/lib/grape/api.rb:76:in `instance_eval'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-1.0.0/lib/grape/api.rb:76:in `block in nest'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-1.0.0/lib/grape/api.rb:76:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-1.0.0/lib/grape/api.rb:76:in `nest'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-1.0.0/lib/grape/dsl/routing.rb:164:in `block in namespace'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-1.0.0/lib/grape/dsl/settings.rb:158:in `within_namespace'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-1.0.0/lib/grape/dsl/routing.rb:161:in `namespace'
/home/git/gitlab/lib/api/groups.rb:74:in `<class:Groups>'
/home/git/gitlab/lib/api/groups.rb:2:in `<module:API>'
/home/git/gitlab/lib/api/groups.rb:1:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:360:in `require_or_load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:184:in `const_missing'
/home/git/gitlab/lib/api/api.rb:123:in `<class:API>'
/home/git/gitlab/lib/api/api.rb:2:in `<module:API>'
/home/git/gitlab/lib/api/api.rb:1:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:360:in `require_or_load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:184:in `const_missing'
/home/git/gitlab/config/initializers/rack_attack.rb:9:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/engine.rb:652:in `block in load_config_initializer'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/engine.rb:651:in `load_config_initializer'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `block in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
/home/git/gitlab/config/environment.rb:5:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
```

**Comment by marmartintsang** [comment]
@sameersbn  could you please help me with this issue ;( Or could i downgrade to a older version of gitlab without using `default_group_visibility` function ?

Here are some references of this issue:

- [https://www.reddit.com/r/gitlab/comments/7b6ahx/nomethoderror_undefined_method_default_group/](https://www.reddit.com/r/gitlab/comments/7b6ahx/nomethoderror_undefined_method_default_group/)
- [https://forum.gitlab.com/t/migration-failed-from-8-4-to-10-0-undefined-method-default-group-visibility/12401](https://forum.gitlab.com/t/migration-failed-from-8-4-to-10-0-undefined-method-default-group-visibility/12401)

thank you very much for your help.

**Comment by nixel2007** [comment]
Try to restore from backup and upgrade through all second point versions.

**Comment by cloudqq** [comment]
I just upgrade my gitlab from 8.0.5 to 10.6.3 and encounter this issue, here is my workaround.

comment the source line in user.rb

`
#/home/git/gitlab/app/models/user.rb

  default_value_for :admin, false
  #<<<< default_value_for(:external) { Gitlab::CurrentSettings.user_default_external }
  default_value_for :can_create_group, gitlab_config.default_can_create_group
`

then override the user.rb with the modified version leverage docker volume mapping. 
`
  gitlab:
    restart: always
    image: sameersbn/gitlab:10.6.3
    depends_on:
    - redis
    - postgresql
    ports:
    - "10080:80"
    - "10022:22"
    volumes:
    - /gitdata/data/gitlab:/home/git/data:Z
    - /home/xxx/user.rb:/home/git/gitlab/app/models/user.rb
    environment:
`

**Comment by jest** [comment]
I succeeded with upgrade first to 9.5.5, and then with upgrade to 10.6.4.

**Comment by kabengwa** [comment]
so what is the solution to this. because i am doing the very first installation on docker and i am getting the same issue when i try to use the :latest version ... should i just settle for the older versions.

**Comment by plakat** [comment]
While upgrading from 7.11.4 to 11.0.1 I was able to mitigate this error by expanding from my initial upgrade path (7.11.4-1 -> 8.0.5-1 -> 11.0.1) to one including each major version in between:
7.11.4-1 -> 8.0.5-1 -> 9.5.5 -> 10.6.4 -> 11.0.1

**Comment by wang19930902** [comment]
Me too!
Remove 2 line for /home/git/gitlab/lib/api/groups.rb:
```
diff --git a/lib/api/groups.rb b/lib/api/groups.rb
index ad16f26f5cc..143b7e6824a 100644
--- a/lib/api/groups.rb
+++ b/lib/api/groups.rb
@@ -12,8 +12,6 @@ module API
         optional :description, type: String, desc: 'The description of the group'
         optional :visibility, type: String,
                               values: Gitlab::VisibilityLevel.string_values,
-                              default: Gitlab::VisibilityLevel.string_level(
-                                Gitlab::CurrentSettings.current_application_settings.default_group_visibility),
                               desc: 'The visibility of the group'
         optional :lfs_enabled, type: Boolean, desc: 'Enable/disable LFS for the projects in this group'
         optional :request_access_enabled, type: Boolean, desc: 'Allow users to request member access'
```
